export const autonomousScenarios = [
  ['SOURCE','New payable','Import creates one obligation and wakeup'],
  ['SOURCE','New source revision','Only the newest amount and acceptance are used'],
  ['SOURCE','Duplicate export','Repeated export creates no duplicate obligation or wakeup'],
  ['SOURCE','Out-of-order export','Older revision cannot overwrite newer data'],
  ['SOURCE','Malformed amount','Excess precision is quarantined'],
  ['SOURCE','Missing party mapping','Unmapped obligation stays blocked until its party arrives'],
  ['SOURCE','Conflicting evidence','Untrusted prose cannot mark delivery accepted'],
  ['SOURCE','Amendment after payment','Paid obligation stays immutable and requires review'],
  ['RECEIPT','Arc customer deposit','One verified deposit is allocated exactly once'],
  ['RECEIPT','Source-chain deposit','Source receipt is recorded without crediting Arc'],
  ['RECEIPT','Unknown payer','Unknown sender remains unmatched'],
  ['RECEIPT','Identical invoices','Two candidate invoices require an owner match decision'],
  ['RECEIPT','Partial payment','Allocation never exceeds actual received units'],
  ['RECEIPT','Overpayment','Extra units do not inflate invoice revenue'],
  ['RECEIPT','Receipt replay','Duplicate observation cannot allocate twice'],
  ['RECEIPT','Internal CCTP mint','Mint is not customer revenue'],
  ['LIQUIDITY','Arc sufficient','Scheduler pays an affordable obligation once'],
  ['LIQUIDITY','One source sufficient','Scheduler funds Arc through CCTP before payout'],
  ['LIQUIDITY','Two sources required','Repeated decisions use remaining source capacity'],
  ['LIQUIDITY','Bridge amount cap','Funding uses multiple capped bridge intents'],
  ['LIQUIDITY','Source cannot cover fee','No unsafe bridge dispatch occurs'],
  ['LIQUIDITY','Protected reserve','Payout respects reserve even with positive balance'],
  ['LIQUIDITY','Source RPC unavailable','Failed chain does not prevent inspection of healthy chain'],
  ['LIQUIDITY','All wallets empty','No payout or bridge dispatch occurs'],
  ['LIQUIDITY','Funds arrive after hold','New liquidity wakes a held obligation'],
  ['LIQUIDITY','Delayed mint','No payout until mint proof has settled'],
  ['TIME','Enter planning window','Window deadline wakes an obligation without new revenue'],
  ['TIME','Near deadline','Soon deadline is persisted separately'],
  ['TIME','Payment deadline','Due deadline survives queue persistence'],
  ['TIME','Update during evaluation','An input update is not lost after the current run'],
  ['TIME','Coalesced events','A burst produces one initial model evaluation'],
  ['TIME','Idle worker ticks','Unchanged state produces no additional model calls'],
  ['TIME','Resume','Pause prevents dispatch and resume wakes it'],
  ['TIME','Restart past deadline','A new scheduler claims overdue durable jobs'],
  ['OWNER','Approve delivery','Exact acceptance request resolves once'],
  ['OWNER','Cancel proposal','Rejection changes neither acceptance nor dispute'],
  ['OWNER','Comment-only instruction','Comment grants no spending override'],
  ['OWNER','Stale proposal','Changed state invalidates approval digest'],
  ['OWNER','Expired proposal','Expired request cannot grant authority'],
  ['OWNER','Double click','Replaying response ID produces one response'],
  ['OWNER','Opposing replies','Only the first resolution can win'],
  ['OWNER','Rejection survives restart','Unchanged rejected proposal stays blocked'],
  ['RECOVERY','Lost payout response','Unknown outcome is never automatically resubmitted'],
  ['RECOVERY','Lost burn response','Unknown burn is never automatically dispatched again'],
  ['RECOVERY','Canonicality changed','Reorg pauses execution and preserves checkpoint'],
  ['RECOVERY','LLM unavailable','Failure is retained with bounded retry'],
  ['RECOVERY','Independent reviewer blocks','A review hold cannot dispatch payment'],
  ['RECOVERY','Telegram unavailable','Telegram failure cannot skip reconciliation workers'],
  ['RECOVERY','Restart after submit','Recovery preserves unknown intent instead of resending'],
  ['RECOVERY','Competing schedulers','Wallet lease permits only one active dispatcher'],
] .map(([group,name,predicate],index)=>({id:`A${String(index+1).padStart(2,'0')}`,group,name,predicate,timeoutMs:30_000,
  liveEligible:['A09','A10','A17','A18','A24','A35'].includes(`A${String(index+1).padStart(2,'0')}`),
  faultMode:group==='RECOVERY'?'OFFLINE_FAULT':'OFFLINE',
}));
