import React from 'react';
import {SOURCE_CHAINS,type State} from '../domain.ts';
import {localSummary,paymentOutcome} from './local-summary.ts';
export const localMoney=(value:string)=>{const n=BigInt(value);return `${(n/1000000n).toLocaleString('en-US')}.${(n%1000000n).toString().padStart(6,'0').replace(/0+$/,'').padEnd(2,'0')}`;};
export const localDate=(value:string)=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Not recorded';
export function LocalOverview({state,navigate}:{state:State;navigate:(tab:string)=>void}){
 const summary=localSummary(state),sim=state.mode==='simulation';const latest=state.runs.at(-1),requests=state.autonomy?.requests.filter(r=>r.status==='OPEN').length??0;
 const pending=state.intents.some(i=>!['SETTLED','SIMULATED','CANCELLED'].includes(i.status))||state.bridgeIntents.some(i=>!['SETTLED','CANCELLED'].includes(i.status));
 const status=state.paused?'Agent paused':pending?'Verifying transactions':requests?'Your decision is needed':!state.autonomy?.enabled?'Setup needed':latest?.status==='RUNNING'?'Agent evaluating':'Agent monitoring';
 const detail=state.paused?'New payments are on hold. Submitted transactions continue to reconcile.':pending?'Submitted operations are awaiting authoritative receipts.':requests?`${requests} request${requests===1?'':'s'} need your approval, cancellation or comment.`:!state.autonomy?.enabled?'Connect your business records and enable evaluations in Setup.':'Monitoring your connected sources for changes.';
 return <>
  <section className="local-agent-status" aria-label="Agent status"><div><h2>{status}</h2><p>{detail}</p>{latest?.status==='ERROR'&&<p className="warning">The last evaluation did not complete. See Agent log for its recorded outcome.</p>}</div><button className="secondary" onClick={()=>navigate(requests?'actions':!state.autonomy?.enabled?'setup':'log')}>{requests?'Review requests':!state.autonomy?.enabled?'Open Setup':'View result'}</button></section>
  <div className="local-totals">{[['Customers paid',summary.received,`${summary.revenues.length} ${sim?'sample':'verified'} receipts`],['Still owed',summary.remaining,`${summary.unpaid.length} unpaid payments`],['Paid to contractors',summary.settled,`${summary.paid.length} ${sim?'simulated payments':'payments confirmed onchain'}`]].map(([title,value,note])=><article key={title}><span>{title}</span><strong>{localMoney(value)} <small>USDC</small></strong><p>{note}</p></article>)}</div>
  <section className="panel local-card"><div className="section-title"><div><h2>Who needs to be paid?</h2><p className="sub">Earliest deadline first</p></div><button className="text-button" onClick={()=>navigate('payments')}>All payments →</button></div><LocalPayables state={state} unpaidOnly/></section>
  <section className="panel local-card"><div className="section-title"><h2>Where did the money come from?</h2><button className="text-button" onClick={()=>navigate('payments')}>View transactions →</button></div>{summary.revenues.map(r=><article className="local-receipt" key={r.id}><div><strong>{r.invoice}</strong><p>{r.sourceChain&&r.sourceChain!=='ARC-TESTNET'?SOURCE_CHAINS[r.sourceChain].label:sim?'Sample customer receipt':'Arc Testnet'}</p></div><b>{localMoney(r.amount)} USDC</b><span className="status">{sim?'Simulation':'Received · verified'}</span></article>)}{!summary.revenues.length&&<p className="empty">{sim?'No sample customer receipt recorded.':'No customer payment has been verified yet.'}</p>}<details className="local-detail"><summary>Transfers to the payment network</summary><p>Customer receipts and transfers to Arc are separate records. Funds in transit are not an available Arc balance.</p><p>{state.bridgeIntents.filter(i=>i.status==='SETTLED'&&i.mintHash).length} transfers confirmed on Arc</p><button className="secondary" onClick={()=>navigate('payments')}>View transfer details</button></details></section>
 </>;
}
export function LocalPayables({state,unpaidOnly=false}:{state:State;unpaidOnly?:boolean}){
 const summary=localSummary(state),items=unpaidOnly?summary.unpaid:[...summary.unpaid,...summary.paid];
 return <>{items.map(o=>{const outcome=paymentOutcome(state,o),decision=[...state.runs].reverse().flatMap(r=>r.decisions).find(d=>d.obligationId===o.id);
 return <article className="local-payable" key={o.id}><div><h3>{o.contractor}</h3><p>{o.title}</p><span className={`status ${outcome?'success':o.disputed?'warning':''}`}>{outcome==='verified'?'Paid · verified':outcome==='simulated'?'Simulated · offchain':o.paid?'Settlement evidence unavailable':o.disputed?'Delivery disputed':o.accepted?'Unpaid':'Delivery needs acceptance'}</span></div><div className="local-payable-amount"><strong>{localMoney(o.amount)} USDC</strong><small>Due {localDate(o.due)}</small></div><details className="local-detail"><summary>Payment details{decision?` · Agent ${({PAY_NOW:'chose payment',FUND_ARC:'chose funding',HOLD:'chose waiting',REQUEST_EVIDENCE:'requested evidence'})[decision.action]}`:''}</summary>{decision&&<p>{decision.reason}</p>}<p className="mono">Recipient: {o.recipient}</p>{state.evidence.filter(e=>e.obligationId===o.id).map(e=><blockquote key={e.id}>{e.text}<small>{e.author}</small></blockquote>)}</details></article>;
 })}{!items.length&&<p className="empty">{state.obligations.some(o=>!o.archived)?'All current payments have completed.':'No work obligation recorded. Connect your business records in Setup.'}</p>}</>;
}
