import React,{useEffect,useState} from 'react';
import type {State} from '../domain.ts';
import {ActionQueue,SourceSettingsPanel,OperationsStatus,GoalPlans} from './AutonomyPanel.tsx';
import {DecisionRecords} from './DecisionRecords.tsx';
import {LiquidityPanel,type LiquidityView} from './LiquidityPanel.tsx';
import {LocalOverview,LocalPayables,localMoney,localDate} from './LocalOverview.tsx';
import {WalletSetup} from './WalletSetup.tsx';
import './local-workspace.css';

const destinations=[['overview','Overview'],['payments','Payments'],['funds','Funds'],['log','Agent log'],['actions','Your decisions'],['setup','Setup']] as const;
const selectedTab=()=>destinations.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'overview';
type LocalState=State&{liquidityAnalysis?:LiquidityView;planner:string;sendEnabled:boolean;bridgeEnabled:boolean;walletProvider:string};
type Props={state:LocalState;busy:string;error:string;connectionError:string;api:(path:string,body?:unknown)=>Promise<any>;refresh:()=>Promise<void>;act:(path:string,body?:unknown)=>Promise<void>;model:React.ReactNode;telegram:React.ReactNode;policy:React.ReactNode;payments:React.ReactNode};
export function LocalWorkspace({state,busy,error,connectionError,api,refresh,act,model,telegram,policy,payments}:Props){
 const [tab,setTab]=useState(selectedTab);
 useEffect(()=>{window.scrollTo({top:0});},[tab]);
 useEffect(()=>{const update=()=>setTab(selectedTab());window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 const navigate=(next:string)=>{const destination=next==='today'?'overview':next==='settings'?'setup':next;location.hash=destination;setTab(destination);};
 const sim=state.mode==='simulation',requests=state.autonomy?.requests.filter(r=>r.status==='OPEN').length??0;
 const titles:Record<string,[string,string]>={overview:['Your payments, in view.','Customer receipts, unpaid work and the latest Agent result.'],payments:['Follow the money.','Contractor payments, customer receipts and transfers to Arc.'],funds:['Funds available to the Agent.','Recorded wallet balances and the limits protecting them.'],log:['What the Agent decided.','Saved evaluations, execution results and operational history.'],actions:['Decisions that need you.','Approve, cancel or leave a comment on the exact request.'],setup:['Set up your workspace.','Connect your model, Agent Wallet and business records.']};
 return <div className="local-workspace"><a href="#main" className="skip" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();}}>Skip to main content</a><div className="local-frame">
  <header className="local-header"><a className="local-brand" href="#overview"><span className="brandmark">s.</span><strong>SettlePilot</strong></a><span className="local-header-label">Your local workspace</span><span className="local-operation"><i/>{state.paused?'Paused':!state.autonomy?.enabled?'Automatic evaluations off':'Automatic evaluations on'}</span></header>
  <div className="local-body"><aside className="local-sidebar"><nav aria-label="Main navigation">{destinations.map(([id,label],index)=><a key={id} className={`local-nav ${tab===id?'active':''}`} href={`#${id}`} aria-current={tab===id?'page':undefined}><NavIcon index={index}/>{label}{id==='actions'&&requests>0&&<span className="local-count">{requests}</span>}</a>)}</nav><div className="local-sidebar-note"><p>Workspace owner<br/>Controls stay on this PC.</p><span>{sim?'Simulation · offchain':'Arc Testnet · 5042002'}</span></div></aside>
  <main id="main" tabIndex={-1} className="local-main"><div className="local-heading"><div><h1>{titles[tab]?.[0]??titles.overview[0]}</h1><p>{titles[tab]?.[1]??titles.overview[1]}</p></div><button className="secondary" disabled={!!busy} onClick={()=>void act('pause',{paused:!state.paused})}>{state.paused?'Resume operations':'Pause operations'}</button></div>
   {sim&&<div className="local-mode-note" role="note">Simulation · sample records and offchain outcomes. No real funds or onchain settlement.</div>}
   {(error||connectionError)&&<div className="notice error" role="alert">{error||connectionError}</div>}
   {requests>0&&tab!=='actions'&&<div className="local-owner-notice"><p><strong>{requests} request{requests===1?'':'s'} need your decision.</strong> The Agent is waiting for your response.</p><button className="secondary" onClick={()=>navigate('actions')}>Review requests</button></div>}
   {tab==='overview'&&<LocalOverview state={state} navigate={navigate}/>}
   {tab==='actions'&&<ActionQueue state={state} api={api} refresh={refresh}/>}
   {tab==='payments'&&<><section className="panel local-card"><h2>Contractor payments</h2><LocalPayables state={state}/></section><details className="panel local-card local-records"><summary>Receipts & transaction records</summary>{payments}</details></>}
   {tab==='funds'&&<><section className="panel local-card"><h2>{sim?'Sample wallet balance':'Arc wallet balance'}</h2><p className="local-balance">{localMoney(state.snapshot.balance)} <small>USDC</small></p><p className="sub">Recorded {localDate(state.snapshot.observedAt)}. Source-chain funds are separate from the Arc balance.</p></section><LiquidityPanel analysis={state.liquidityAnalysis}/>{policy}</>}
   {tab==='log'&&<><DecisionRecords state={state} api={api}/><details className="panel local-card local-records"><summary>Agent plans & connection health</summary><GoalPlans state={state}/><OperationsStatus state={state}/></details><section className="panel local-card"><h2>Activity log</h2>{[...state.events].reverse().slice(0,100).map(e=><article className="local-event" key={e.id}><time>{localDate(e.at)}</time><div><strong>{e.type.replaceAll('_',' ').toLowerCase()}</strong><p>{e.detail}</p></div></article>)}{!state.events.length&&<p className="empty">No activity recorded yet.</p>}{state.events.length>100&&<p className="sub">Showing the latest 100 events. Complete history remains in your local database.</p>}</section></>}
   {tab==='setup'&&<><div className="local-setup-intro"><h2>Connect first. Enable operations when ready.</h2><p>Save your model, connect your own testnet wallet, then choose your business source. Spending authority and transfers are separate controls.</p><div>{[['model','Model'],['wallet','Agent Wallet'],['source','Business records']].map(([id,label],index)=><button className="text-button" key={id} onClick={()=>document.getElementById(`${id}-setup`)?.scrollIntoView({block:'start'})}>{index+1}. {label}</button>)}</div></div><div id="model-setup">{model}</div><WalletSetup api={api}/><div id="source-setup"><SourceSettingsPanel api={api} refresh={refresh}/></div><details className="panel local-card local-records"><summary>Optional Telegram notifications</summary>{telegram}</details><details className="panel local-card local-records"><summary>Current authority & payment limits</summary>{policy}</details></>}
   <footer>{sim?'Simulation · not an onchain payment.':'Testnet USDC · every completed payment requires verified chain evidence.'}<span>Local time · {Intl.DateTimeFormat().resolvedOptions().timeZone}</span></footer>
  </main></div></div>{busy&&<div role="status" className="working">Processing request…</div>}</div>;
}
function NavIcon({index}:{index:number}){const paths=['M3 3h6v6H3z M13 3h6v6h-6z M3 13h6v6H3z M13 13h6v6h-6z','M5 3h10l3 3v14H5z M9 10h5 M9 14h5','M3 6h16v12H3z M3 6V4h13 M14 12h5','M5 4h14v16H5z M9 8h6 M9 12h6 M9 16h4','M4 4h16v12h-9l-5 4v-4H4z M8 8h8 M8 12h5','M11 4v3 M11 15v3 M4 11h3 M15 11h3 M6 6l2 2 M14 14l2 2 M6 16l2-2 M14 8l2-2'];return <svg width="18" height="18" viewBox="0 0 22 22" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[index]}/>{index===5&&<circle cx="11" cy="11" r="4"/>}</svg>;}
