import React,{useEffect,useState,type FormEvent} from 'react';
import type {ModelLimits,ModelControl} from '../model-requests.ts';
import type {modelUsageSummary} from '../model-usage-summary.ts';
type View={limits:ModelLimits;summary:ReturnType<typeof modelUsageSummary>;blocks:ModelControl['blocks'];archivedRequests:number};
const usd=(nano:number)=>`$${(nano/1e9).toFixed(4)}`;
export function ModelUsage({api}:{api:(path:string,body?:unknown)=>Promise<any>}){
 const [view,setView]=useState<View>(),[limits,setLimits]=useState<ModelLimits>(),[confirmation,setConfirmation]=useState(false),[resetConfirmation,setResetConfirmation]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;const load=async()=>{try{const value=await api('model-usage/summary');if(active){setView(value);setLimits(previous=>previous??value.limits);setError('');}}catch{if(active)setError('Model usage is unavailable. Reconnect the local panel to refresh it.');}};void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer);};},[]);
 async function request(path:string,body:unknown,message:string){setBusy(true);setError('');setNotice('');try{await api(path,body);setView(await api('model-usage/summary'));setConfirmation(false);setResetConfirmation(false);setNotice(message);}catch(e){setError(e instanceof Error&&e.message==='AGENT_RUN_IN_PROGRESS'?'Wait for the current evaluation to finish.':'The settings could not be saved. Check the limits and connection.');}finally{setBusy(false);}}
 const s=view?.summary;
 return <section className="panel local-card model-usage"><span className="eyebrow">MODEL USAGE</span><h2>AI cost & budget</h2><p className="sub">Usage is counted per UTC day. Estimates cover known model prices; your provider determines the bill.</p>{error&&<p role="alert" className="settings-feedback error">{error}</p>}{notice&&<p role="status" className="settings-feedback success">{notice}</p>}
 {s&&view&&<><div className="local-totals"><article><span>Requests today</span><strong>{s.requests}</strong><p>{s.remainingRequests} requests remaining</p></article><article><span>Reported tokens</span><strong>{s.reportedTokens.toLocaleString()}</strong><p>{s.reservedTokens.toLocaleString()} tokens reserved · {s.remainingTokens.toLocaleString()} remaining</p></article><article><span>Known-price estimate</span><strong>{usd(s.estimatedCostNanoUsd)}</strong><p>{usd(s.reservedCostNanoUsd)} reserved · {usd(s.remainingCostNanoUsd)} known-price allowance left</p></article></div><p className="note">{s.unpricedRequests} requests have unavailable pricing. {s.unresolvedRequests} outcomes retain reservations. Allowances reset {new Date(s.resetsAt).toLocaleString()} (00:00 UTC).</p>
 {Object.entries(view.blocks).map(([provider,block])=>block&&<p className="notice" key={provider}><strong>{provider==='planner'?'Decision model':'Review model'}: {block.code.replaceAll('_',' ').toLowerCase()}</strong>{block.retryAt?` · earliest retry ${new Date(block.retryAt).toLocaleString()}`:' · fix the provider connection or billing first'}</p>)}
 </>}
 {limits&&<details className="local-detail"><summary>Set model usage limits</summary><form onSubmit={(e:FormEvent)=>{e.preventDefault();void request('model-usage/limits',{confirmed:true,limits},'Limits saved. Existing usage, reservations and pause state are preserved.');}}><div className="credential-grid">{(['maxRunRequests','maxDayRequests','maxRunTokens','maxDayTokens','maxRunCostNanoUsd','maxDayCostNanoUsd']as const).map(key=>{const cost=key.includes('Cost'),labels:Record<string,string>={maxRunRequests:'Requests per evaluation',maxDayRequests:'Requests per UTC day',maxRunTokens:'Tokens per evaluation',maxDayTokens:'Tokens per UTC day',maxRunCostNanoUsd:'Estimated USD per evaluation',maxDayCostNanoUsd:'Estimated USD per UTC day'};return <label key={key} htmlFor={`limit-${key}`}>{labels[key]}<input id={`limit-${key}`} type="number" min={cost?'0.000001':'1'} step={cost?'0.000001':'1'} value={cost?limits[key]/1e9:limits[key]} onChange={e=>{setLimits(old=>({...old!,[key]:cost?Math.round(Number(e.target.value)*1e9):Number(e.target.value)}));setConfirmation(false);}} required/></label>;})}</div><p className="note">Unknown-price models still consume request and token limits. This estimate is not a guaranteed provider billing cap.</p><label htmlFor="limits-confirm"><input id="limits-confirm" type="checkbox" checked={confirmation} onChange={e=>setConfirmation(e.target.checked)}/> Apply these limits without resetting usage.</label><button className="primary" type="submit" disabled={busy||!confirmation}>Save usage limits</button></form></details>}
 <details className="local-detail"><summary>Recover a blocked model connection</summary><p>After fixing credentials or provider billing, clear connection blocks to allow a retry. Consumed usage and budgets remain enforced.</p><label htmlFor="model-reset-confirm"><input id="model-reset-confirm" type="checkbox" checked={resetConfirmation} onChange={e=>setResetConfirmation(e.target.checked)}/> I have fixed the provider issue and want to allow a retry.</label><button className="secondary" disabled={busy||!resetConfirmation} onClick={()=>void request('model-usage/reset-blocks',{confirmed:true},'Connection blocks cleared. Usage and pause state are preserved.')}>Clear connection blocks</button></details>
 </section>;
}
