import React,{useEffect,useState,type FormEvent} from 'react';
import {display,SOURCE_CHAINS,SOURCE_CHAIN_NAMES,type State,type SourceChain} from '../domain.ts';
type Api=(path:string,body?:unknown)=>Promise<any>;
const errorText:Record<string,string>={AUTHORITY_CHANGED:'The wallet state or permission changed. Refresh and review the latest scope.',RECONCILE_REQUIRED:'Submitted operations must finish reconciliation before granting a new scope.',PAUSE_BEFORE_SETUP:'Pause operations before editing permission.',AGENT_RUN_IN_PROGRESS:'Wait for the current evaluation to finish.',CONNECT_TESTNET_WALLET_FIRST:'Connect your testnet wallet and restart the panel first.',INVALID_RECIPIENT:'Recipients must be unique wallet addresses and cannot include the Agent Wallet.',INVALID_AUTHORITY_LIMITS:'Check payment, total budget and bridge limits.',BUDGET_BELOW_SPENT:'The total budget cannot be below payments already completed.',INVALID_AUTHORITY_EXPIRY:'Choose a future expiry within one year.',GRANT_AUTHORITY_FIRST:'Grant a current spending scope first.',GRANT_BRIDGE_AUTHORITY_FIRST:'Include crosschain funding in the spending scope first.',WRONG_CHAIN:'The connection did not verify Arc Testnet.',STALE_BALANCE:'The balance could not be verified recently. Check the wallet connection.'};
export function OwnerAuthority({state,api,refresh}:{state:State&{sendEnabled:boolean;bridgeEnabled:boolean};api:Api;refresh:()=>Promise<void>}){
 const p=state.policy,b=state.bridgePolicy;
 const [recipients,setRecipients]=useState(p.allowlist.join('\n')),[reserve,setReserve]=useState(display(p.reserve)),[gas,setGas]=useState(display(p.gasLimit)),[per,setPer]=useState(display(p.perObligation)),[total,setTotal]=useState(display(p.totalBudget));
 const localExpiry=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 const [expires,setExpires]=useState(localExpiry(Date.parse(p.authorityExpiresAt)>Date.now()?p.authorityExpiresAt:new Date(Date.now()+7*86400000).toISOString()));
 const [bridge,setBridge]=useState(b.enabled),[chains,setChains]=useState<SourceChain[]>(b.sourceChains),[maxBridge,setMaxBridge]=useState(display(b.maxAmount)),[fee,setFee]=useState(display(b.maxFee));
 type ReviewedScope={confirmed:true;policyVersion:number;financialVersion:number;allowlist:string[];reserve:string;gasLimit:string;perObligation:string;totalBudget:string;authorityExpiresAt:string;bridge:{enabled:boolean;sourceChains:SourceChain[];maxAmount:string;maxFee:string}};
 const [review,setReview]=useState<ReviewedScope>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState<{error:boolean;text:string}>();
 const [execution,setExecution]=useState({sendEnabled:state.sendEnabled,bridgeEnabled:state.bridgeEnabled}),[executionConsent,setExecutionConsent]=useState(false),[restart,setRestart]=useState(false);
 useEffect(()=>{let active=true;void api('authority-settings').then(v=>{if(active){setExecution(v.execution);setRestart(v.execution.sendEnabled!==state.sendEnabled||v.execution.bridgeEnabled!==state.bridgeEnabled);}}).catch(()=>{if(active)setFeedback({error:true,text:'Saved execution switches could not be loaded.'});});return()=>{active=false;};},[]);
 async function submit(path:string,body:unknown,message:string){setBusy(true);setFeedback(undefined);try{await api(path,body);setReview(undefined);setConfirmed(false);setFeedback({error:false,text:message});await refresh();return true;}catch(e){setFeedback({error:true,text:errorText[e instanceof Error?e.message:'']??'The permission could not be saved. Check the fields and wallet connection.'});return false;}finally{setBusy(false);}}
 const testnet=state.mode==='testnet';
 function prepare(event:FormEvent){event.preventDefault();setFeedback(undefined);setConfirmed(false);setReview({confirmed:true,policyVersion:p.version,financialVersion:state.financialVersion,allowlist:recipients.split(/[\n,]/).map(s=>s.trim()).filter(Boolean),reserve,gasLimit:gas,perObligation:per,totalBudget:total,authorityExpiresAt:new Date(expires).toISOString(),bridge:{enabled:bridge,sourceChains:chains,maxAmount:maxBridge,maxFee:fee}});}
 return <section id="authority-setup" className="panel local-card owner-authority"><span className="eyebrow">STEP 4 · SPENDING PERMISSION</span><h2>What may the Agent pay?</h2><p className="sub">You choose the scope. The Agent makes payment decisions within it. Saving permission leaves operations paused or off until you enable them.</p>
 <p className="note">{!testnet?'Connect your Agent Wallet and restart before granting permission.':p.enabled&&Date.parse(p.authorityExpiresAt)>Date.now()?`Permission active until ${new Date(p.authorityExpiresAt).toLocaleString()}. Version ${p.version}.`:p.enabled?'Permission expired. Review the scope to renew it.':'No active spending permission.'}</p>
 {feedback&&<p className={`settings-feedback ${feedback.error?'error':'success'}`} role={feedback.error?'alert':'status'}>{feedback.text}</p>}
 <form onSubmit={prepare}><fieldset className="credential-group" disabled={!testnet||busy||!!review}><legend>Recipients & payment limits</legend>
 <label htmlFor="authority-recipients">Approved recipients<textarea id="authority-recipients" rows={3} value={recipients} onChange={e=>setRecipients(e.target.value)} required spellCheck={false}/><small>One recipient address per line. Only these recipients can receive payments.</small></label>
 {(state.autonomy?.parties??[]).filter(party=>party.address!==p.sender).map(party=><button className="text-button" type="button" key={party.id} onClick={()=>setRecipients(previous=>[...new Set([...previous.split('\n').filter(Boolean),party.address])].join('\n'))}>Add {party.name}</button>)}
 <div className="credential-grid">{[['authority-reserve','Keep on Arc (USDC)',reserve,setReserve],['authority-gas','Maximum payment gas (USDC)',gas,setGas],['authority-per','Maximum per obligation (USDC)',per,setPer],['authority-total','Total payout budget (USDC)',total,setTotal]].map(([id,label,value,setter])=><label key={id as string} htmlFor={id as string}>{label as string}<input id={id as string} type="number" min="0" step="0.000001" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} required/></label>)}<label htmlFor="authority-expiry">Permission expires (your local time)<input id="authority-expiry" type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)} required/></label></div>
 <p className="note">Total budget includes payments already completed in this workspace. Renewal keeps the payment history and does not reset spent USDC.</p>
 <label className="toggle-row" htmlFor="authority-bridge"><span><strong>Allow funding Arc from other chains</strong><small>Verified USDC only, within a separate amount and fee scope.</small></span><input id="authority-bridge" type="checkbox" checked={bridge} onChange={e=>setBridge(e.target.checked)}/></label>
 {bridge&&<><div className="authority-chain-options">{SOURCE_CHAIN_NAMES.map(chain=><label key={chain} htmlFor={`authority-${chain}`}><input id={`authority-${chain}`} type="checkbox" checked={chains.includes(chain)} onChange={e=>setChains(old=>e.target.checked?[...old,chain]:old.filter(c=>c!==chain))}/>{SOURCE_CHAINS[chain].label}</label>)}</div><div className="credential-grid"><label htmlFor="authority-bridge-max">Maximum per bridge (USDC)<input id="authority-bridge-max" type="number" min="0.000001" step="0.000001" value={maxBridge} onChange={e=>setMaxBridge(e.target.value)} required/></label><label htmlFor="authority-fee">Maximum bridge fee (USDC)<input id="authority-fee" type="number" min="0" step="0.000001" value={fee} onChange={e=>setFee(e.target.value)} required/></label></div></>}
 <button className="primary" type="submit">Review spending permission</button></fieldset></form>
 {review&&<div className="authority-review" role="region" aria-label="Review spending permission"><h3>Confirm this exact scope</h3><p>Wallet <span className="mono">{p.sender}</span></p><div aria-label="Recipients in this permission">{review.allowlist.map((address:string)=><p className="mono" key={address}>{address}</p>)}</div><p>{review.allowlist.length} recipients · up to {review.perObligation} USDC per obligation · {review.totalBudget} USDC total · keep {review.reserve} USDC on Arc. Maximum gas: {review.gasLimit} USDC per payment.</p><p>Expires {new Date(review.authorityExpiresAt).toLocaleString()}. {review.bridge.enabled?`CCTP from ${review.bridge.sourceChains.map((chain:SourceChain)=>SOURCE_CHAINS[chain].label).join(", ")}, up to ${review.bridge.maxAmount} USDC per bridge and ${review.bridge.maxFee} USDC fee.`:'Crosschain funding disabled.'}</p><label htmlFor="authority-confirm"><input id="authority-confirm" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I authorize the Agent to operate within this scope on Arc Testnet.</label><div className="settings-actions"><button className="primary" disabled={!confirmed||busy} onClick={()=>void submit('authority-settings',review,'Spending permission saved. Operations have not been resumed.')}>Grant permission</button><button className="secondary" disabled={busy} onClick={()=>setReview(undefined)}>Edit scope</button></div></div>}
 {testnet&&p.enabled&&<button className="secondary" disabled={busy} onClick={()=>void submit('authority-settings/revoke',{confirmed:true,policyVersion:p.version},'Permission revoked. New work is paused; submitted transactions continue to reconcile.')}>Revoke permission & pause</button>}
 <details className="local-detail"><summary>Enable payment sending</summary><p>Saved switches apply after restarting the panel. Granting permission and enabling evaluations are separate steps.</p><p>Currently running: payments {state.sendEnabled?'on':'off'} · CCTP {state.bridgeEnabled?'on':'off'}.</p><label htmlFor="execution-send"><input id="execution-send" type="checkbox" checked={execution.sendEnabled} disabled={!testnet||busy} onChange={e=>{setExecution(v=>({...v,sendEnabled:e.target.checked}));setExecutionConsent(false);}}/> Send testnet payments</label><label htmlFor="execution-bridge"><input id="execution-bridge" type="checkbox" checked={execution.bridgeEnabled} disabled={!testnet||busy} onChange={e=>{setExecution(v=>({...v,bridgeEnabled:e.target.checked}));setExecutionConsent(false);}}/> Submit CCTP transfers</label><label htmlFor="execution-confirm"><input id="execution-confirm" type="checkbox" checked={executionConsent} onChange={e=>setExecutionConsent(e.target.checked)}/> I confirm these sending switches for this wallet.</label><button className="primary" disabled={!testnet||busy||!executionConsent} onClick={()=>{void submit('authority-settings/execution',{confirmed:true,policyVersion:p.version,...execution},'Sending switches saved. Stop the panel using Agent Wallet setup, then reopen Open-SettlePilot.vbs.').then(ok=>{if(ok)setRestart(true);});}}>Save sending switches</button>{restart&&<p role="status">Restart required to apply saved switches. Use Stop panel to apply setup in the Agent Wallet section.</p>}</details>
 </section>;
}
