import React,{useEffect,useState,type FormEvent} from 'react';
type WalletView={cliInstalled:boolean;cliVersion:string;mode:string;sender?:string;rpcConfigured:boolean;restartRequired:boolean;sendingEnabled:boolean;termsAccepted?:boolean;sessionValid?:boolean;wallets?:{address:string;network:string}[];terms?:{currentVersion:number;termsOfUseUrl:string;privacyPolicyUrl:string;termsNotice:string}};
const messages:Record<string,string>={CIRCLE_CLI_NOT_INSTALLED:'Install Circle CLI 1.1.4 once, then refresh this page.',CIRCLE_AGENT_REQUEST_FAILED:'Circle could not complete the request. Check the CLI installation, session or OTP, then try again.',CIRCLE_SESSION_ALREADY_CONNECTED:'A testnet session is already connected. Use its wallets below.',CIRCLE_TERMS_REQUIRED:'Review and accept the current Circle Terms first.',REVIEW_CURRENT_TERMS:'Refresh the current Terms and review them before accepting.',OTP_REQUEST_EXPIRED:'This login request expired or was used. Request a new code.',AGENT_WALLET_NOT_FOUND:'Choose an Arc Testnet wallet from your connected Circle session.',ARC_NETWORK_CHECK_FAILED:'The RPC did not verify Arc Testnet (5042002). Check its URL and connection.',PAUSE_BEFORE_SETUP:'Pause operations before changing wallet setup.',AGENT_RUN_IN_PROGRESS:'Wait for the current evaluation to finish.',RECONCILE_REQUIRED:'Wait for submitted payments and bridges to reconcile.',EXISTING_WALLET_CHANGE_REQUIRES_MIGRATION:'This workspace is bound to another wallet. Its financial history requires a reviewed migration.',EXISTING_POLICY_REQUIRES_REVIEW:'An existing policy has a different wallet or network. Review it before changing setup.',LOCAL_WORKER_BUSY:'A background check is finishing. Try stopping the panel again shortly.'};
export function WalletSetup({api}:{api:(path:string,body?:unknown)=>Promise<any>}){
 const [view,setView]=useState<WalletView>();const [busy,setBusy]=useState(''),[feedback,setFeedback]=useState<{error:boolean;message:string}>();
 const [email,setEmail]=useState(''),[otp,setOtp]=useState(''),[otpRequired,setOtpRequired]=useState(false),[consent,setConsent]=useState(false),[sender,setSender]=useState(''),[rpc,setRpc]=useState(''),[stopped,setStopped]=useState(false);
 useEffect(()=>{let active=true;void api('wallet-settings').then(v=>{if(active){setView(v);setSender(v.sender??'');}}).catch(()=>{if(active)setFeedback({error:true,message:'Wallet setup is unavailable.'});});return()=>{active=false;};},[]);
 async function run(action:string,body:unknown={},success?:string){setBusy(action);setFeedback(undefined);try{
  const result=await api(`wallet-settings${action==='save'?'':'/'+action}`,body);
  if(action==='inspect'){setView(result);setConsent(false);setSender(result.sender??result.wallets?.[0]?.address??'');}
  if(action==='login')setOtpRequired(true);
  if(action==='otp'){setOtpRequired(false);setOtp('');}
  if(action==='save'){setView(previous=>({...previous!,...result}));setRpc('');}
  if(['otp','terms','create'].includes(action)){const next=await api('wallet-settings/inspect',{});setView(next);setSender(next.sender??next.wallets?.[0]?.address??'');}
  if(success)setFeedback({error:false,message:success});
 }catch(error){setFeedback({error:true,message:messages[error instanceof Error?error.message:'']??'The setup request could not be completed. Check the supplied fields and try again.'});}finally{setBusy('');}}
 async function stop(){setBusy('stop');try{await api('local/stop',{confirmed:true});setStopped(true);setFeedback({error:false,message:'Panel stopped. Double-click Open-SettlePilot.vbs to reopen with the saved wallet configuration.'});}catch(error){setFeedback({error:true,message:messages[error instanceof Error?error.message:'']??'The panel could not stop safely.'});}finally{setBusy('');}}
 return <section id="wallet-setup" className="panel local-card wallet-setup"><div className="section-title"><div><span className="eyebrow">STEP 2 · PAYMENT CONNECTION</span><h2>Your Agent Wallet</h2><p className="sub">Use your own Circle Agent Wallet on Arc Testnet. No private key is needed.</p></div><span className="status">{view?.mode==='testnet'?'Testnet workspace':view?.restartRequired?'Restart required':view?.sessionValid?'Circle connected':'Not connected'}</span></div>
  {!view?.cliInstalled&&<div className="note"><p>Install the supported Circle CLI once on this PC:</p><code>npm install -g @circle-fin/cli@1.1.4</code><p>After installation, return here and check the connection. The panel uses the CLI session belonging to your Windows account.</p></div>}
  <button className="secondary" disabled={!!busy||stopped} onClick={()=>void run('inspect')}>{busy==='inspect'?'Checking…':'Check Circle connection'}</button>
  {view?.terms&&<div className="local-detail"><h3>Circle Terms</h3><p className="terms-notice">{view.terms.termsNotice}</p><p><a href={view.terms.termsOfUseUrl} target="_blank" rel="noreferrer">Terms of Use</a> · <a href={view.terms.privacyPolicyUrl} target="_blank" rel="noreferrer">Privacy Policy</a></p><label className="setup-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have read and agree to these Terms and authorize recording acceptance on this PC.</label><button className="primary" disabled={!consent||!!busy} onClick={()=>void run('terms',{confirmed:true,version:view.terms!.currentVersion},'Acceptance recorded.')}>Accept Circle Terms</button></div>}
  {view?.termsAccepted&&!view.sessionValid&&<form className="local-setup-form" onSubmit={(e:FormEvent)=>{e.preventDefault();void run(otpRequired?'otp':'login',otpRequired?{otp}:{email},otpRequired?'Circle session connected.':'Code sent. Enter the OTP from your email.');}}><h3>Sign in to Circle testnet</h3>{otpRequired?<label>One-time code<input value={otp} type="password" autoComplete="one-time-code" onChange={e=>setOtp(e.target.value)} required placeholder="ABC-123456"/></label>:<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>}<div className="settings-actions"><button className="primary" disabled={!!busy}>{otpRequired?'Verify code':'Send sign-in code'}</button>{otpRequired&&<button className="secondary" type="button" disabled={!!busy} onClick={()=>{setOtpRequired(false);setOtp('');}}>Start a new login</button>}</div><p className="sub">Testnet only. Codes are not saved in SettlePilot history or browser storage.</p></form>}
  {view?.sessionValid&&!(view.wallets?.length)&&<div className="note"><p>Signed in. No Arc Testnet Agent Wallet was found.</p><button className="primary" disabled={!!busy} onClick={()=>void run('create',{confirmed:true},'Testnet wallets created.')}>Create testnet Agent Wallet</button></div>}
  {!!view?.wallets?.length&&<form className="local-setup-form" onSubmit={e=>{e.preventDefault();void run('save',{sender,...(rpc?{rpcUrl:rpc}:{})},'Wallet configuration saved. Transfers remain under the existing authority and execution gates.');}}><label>Arc Testnet Agent Wallet<select value={sender} onChange={e=>setSender(e.target.value)} required>{view.wallets.map(w=><option key={w.address} value={w.address}>{w.address}</option>)}</select></label><label>Arc Testnet RPC URL<input type="password" value={rpc} onChange={e=>setRpc(e.target.value)} autoComplete="off" required={!view.rpcConfigured} placeholder={view.rpcConfigured?'RPC saved · leave blank to keep it':'https://your-private-arc-rpc'}/><small>Use your private Arc RPC. The URL is stored locally and not returned to the page.</small></label><button className="primary" disabled={!!busy||stopped}>Verify network & save wallet</button><p className="note">A first connection creates an empty testnet workspace with payment authority and transfers disabled. Setup never imports demonstration funds or grants spending permission.</p></form>}
  {view?.sender&&<p className="mono">Current operating wallet: {view.sender}</p>}
  {(view?.restartRequired||view?.mode==='testnet')&&<div className="note"><h3>Apply startup settings</h3><p>When wallet or sending settings require a restart, pause operations and let submitted transactions reconcile. Stop this panel and reopen <strong>Open-SettlePilot.vbs</strong>. The browser opens with the backend running hidden.</p><button className="secondary" disabled={!!busy||stopped} onClick={()=>void stop()}>{stopped?'Panel stopped':'Stop panel to apply setup'}</button></div>}
  {feedback&&<p className={`settings-feedback ${feedback.error?'error':'success'}`} role={feedback.error?'alert':'status'}>{feedback.message}</p>}
 </section>;
}
